/* Folio 1.0.0 — local-first application. No remote services or telemetry. */
(() => {
'use strict';
const KEY='folio.data.v1', MAX=2500000;
const $=(q,r=document)=>r.querySelector(q);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const i=(name,cls='')=>{const a=window.FOLIO_ICONS[name]||window.FOLIO_ICONS.folder;return `<svg class="icon ${cls}" viewBox="0 0 ${a[0]} ${a[1]}" aria-hidden="true"><path d="${a[2]}"></path></svg>`;};
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(Number(n)||0)+' ₽';
const number=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(Number(n)||0);
const localDate=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return localDate(d);};
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,11);
const parseDate=s=>new Date(s+'T12:00:00');
const prettyDate=(s,long=false)=>s?parseDate(s).toLocaleDateString('ru-RU',{day:'numeric',month:long?'long':'short'}).replace('.',''):'Без срока';
const when=s=>s===day()?'Сегодня':s===day(1)?'Завтра':s===day(-1)?'Вчера':prettyDate(s);
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const monthLabel=d=>d.toLocaleDateString('ru-RU',{month:'long',year:'numeric'}).replace(' г.','');
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(parseDate(s).getTime())&&localDate(parseDate(s))===s;
const categories={design:{label:'Дизайн',icon:'palette',color:'sage'},web:{label:'Веб-разработка',icon:'code',color:'blue'},mobile:{label:'Приложение',icon:'phone',color:'peach'},other:{label:'Другое',icon:'folder',color:'slate'}};
const statuses={active:'В работе',paused:'На паузе',done:'Завершён'};
const priorities={normal:'Обычный',high:'Высокий'};
let state, recovery=false, saveFailed=false, installPrompt=null;
let ui={tab:'home',project:null,projectFilter:'all',taskFilter:'today',query:'',month:monthKey(new Date()),modal:null,modalData:null};
function seed(){
 const now=new Date(),m=monthKey(now),last=new Date(now.getFullYear(),now.getMonth()-1,12),prev=new Date(now.getFullYear(),now.getMonth()-2,10);
 return {version:1,demo:true,profile:{name:'Артём',goal:60000,theme:'light'},projects:[
 {id:'p1',name:'Айдентика для FORMA',client:'FORMA Studio',budget:28000,deadline:day(5),category:'design',status:'active',notes:'Лаконичная айдентика для студии интерьеров. Логотип, палитра, типографика и руководство по стилю.',created:day(-8)},
 {id:'p2',name:'Сайт кофейни',client:'North Coffee',budget:35000,deadline:day(9),category:'web',status:'active',notes:'Небольшой сайт с меню, историей кофейни и формой обратной связи. Адаптация под телефон обязательна.',created:day(-5)},
 {id:'p3',name:'Приложение для йоги',client:'Soft Sunday',budget:45000,deadline:day(16),category:'mobile',status:'paused',notes:'Мобильный интерфейс: подборка практик, расписание и личный прогресс.',created:day(-3)},
 {id:'p4',name:'Лендинг мастерской',client:'Oak & Co.',budget:18000,deadline:day(-3),category:'web',status:'done',notes:'Проект завершён. Все материалы переданы клиенту.',created:day(-23)}],tasks:[
 {id:'t1',title:'Собрать мудборд',project:'p1',due:day(-2),priority:'normal',done:true},
 {id:'t2',title:'Подготовить палитру',project:'p1',due:day(-1),priority:'normal',done:true},
 {id:'t3',title:'Показать варианты логотипа',project:'p1',due:day(),priority:'high',done:false},
 {id:'t4',title:'Сверстать первый экран',project:'p2',due:day(),priority:'normal',done:false},
 {id:'t5',title:'Уточнить состав меню',project:'p2',due:day(1),priority:'normal',done:false},
 {id:'t6',title:'Прототип экрана практики',project:'p3',due:day(3),priority:'normal',done:false},
 {id:'t7',title:'Адаптировать сайт под телефон',project:'p2',due:day(4),priority:'high',done:false},
 {id:'t8',title:'Передать макеты и исходники',project:'p4',due:day(-3),priority:'normal',done:true}],payments:[
 {id:'r1',project:'p1',projectName:'Айдентика для FORMA',amount:14000,date:localDate(now),note:'Предоплата 50%'},
 {id:'r2',project:'p2',projectName:'Сайт кофейни',amount:7500,date:localDate(now),note:'Первый этап'},
 {id:'r3',project:'p4',projectName:'Лендинг мастерской',amount:18000,date:localDate(now),note:'Полная оплата'},
 {id:'r4',project:'',projectName:'Архивный заказ',amount:26000,date:localDate(last),note:'Демо: прошлый месяц'},
 {id:'r5',project:'',projectName:'Архивный заказ',amount:17500,date:localDate(prev),note:'Демо: позапрошлый месяц'}]};
}
function validate(d){
 const text=(v,n,empty=true)=>typeof v==='string'&&v.length<=n&&(empty||v.trim().length>0);
 const id=v=>text(v,80,false)&&/^[\w-]+$/.test(v);
 const cash=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=999999999;
 if(!d||d.version!==1||!d.profile||!Array.isArray(d.projects)||!Array.isArray(d.tasks)||!Array.isArray(d.payments))throw Error('Это не резервная копия Folio v1.');
 if(!text(d.profile.name,40,false)||!cash(d.profile.goal)||d.profile.goal<1||!['light','dark','system'].includes(d.profile.theme)||typeof d.demo!=='boolean')throw Error('В копии некорректные настройки.');
 if(d.projects.length>5000||d.tasks.length>20000||d.payments.length>20000)throw Error('Слишком много записей в резервной копии.');
 for(const p of d.projects)if(!id(p.id)||!text(p.name,80,false)||!text(p.client,60)||!cash(p.budget)||!(p.deadline===''||validDate(p.deadline))||!Object.prototype.hasOwnProperty.call(categories,p.category)||!Object.prototype.hasOwnProperty.call(statuses,p.status)||!text(p.notes,2000)||!validDate(p.created))throw Error('В копии некорректный проект.');
 const ps=new Set(d.projects.map(p=>p.id));
 for(const t of d.tasks)if(!id(t.id)||!text(t.title,160,false)||!text(t.project,80)||!(t.project===''||ps.has(t.project))||!(t.due===''||validDate(t.due))||!Object.prototype.hasOwnProperty.call(priorities,t.priority)||typeof t.done!=='boolean')throw Error('В копии некорректная задача.');
 for(const p of d.payments)if(!id(p.id)||!text(p.project,80)||!(p.project===''||ps.has(p.project))||!text(p.projectName,80)||!cash(p.amount)||p.amount<=0||!validDate(p.date)||!text(p.note,200))throw Error('В копии некорректный платёж.');
 for(const a of [d.projects,d.tasks,d.payments])if(new Set(a.map(x=>x.id)).size!==a.length)throw Error('В копии повторяются идентификаторы.');
 // Select known properties: no executable content or prototype merging.
 return {version:1,demo:d.demo,profile:{name:d.profile.name.trim(),goal:d.profile.goal,theme:d.profile.theme},projects:d.projects.map(p=>({id:p.id,name:p.name.trim(),client:p.client,budget:p.budget,deadline:p.deadline,category:p.category,status:p.status,notes:p.notes,created:p.created})),tasks:d.tasks.map(t=>({id:t.id,title:t.title.trim(),project:t.project,due:t.due,priority:t.priority,done:t.done})),payments:d.payments.map(p=>({id:p.id,project:p.project,projectName:p.projectName,amount:p.amount,date:p.date,note:p.note}))};
}
function load(){
 try{const raw=localStorage.getItem(KEY);if(raw){state=validate(JSON.parse(raw));}else{state=seed();localStorage.setItem(KEY,JSON.stringify(state));}}
 catch(e){state=seed();recovery=true;}
}
function save(){
 if(recovery){toast('Сначала сохраните или сбросьте повреждённые данные в настройках.',true);return false;}
 try{const s=JSON.stringify(state);if(s.length>MAX)throw Error();localStorage.setItem(KEY,s);saveFailed=false;return true;}
 catch(e){saveFailed=true;toast('Не удалось сохранить. Освободите память или экспортируйте данные.',true);return false;}
}
function commit(fn,message){
 const before=JSON.stringify(state);fn();if(!save()){state=JSON.parse(before);render();return false;}if(message)toast(message);return true;
}
function applyTheme(){const t=state.profile.theme;const dark=t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';$('meta[name="theme-color"]').content=dark?'#181e1a':'#f6f5f1';}
function toast(text,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=text;$('#toasts').replaceChildren(el);setTimeout(()=>el.remove(),3500);}
function getProject(id){return state.projects.find(p=>p.id===id);}
function paid(id){return state.payments.filter(x=>x.project===id).reduce((s,x)=>s+x.amount,0);}
function sumMonth(m){return state.payments.filter(x=>x.date.startsWith(m)).reduce((s,x)=>s+x.amount,0);}
function progress(id){const tasks=state.tasks.filter(t=>t.project===id);return {all:tasks.length,done:tasks.filter(t=>t.done).length,percent:tasks.length?Math.round(tasks.filter(t=>t.done).length/tasks.length*100):0};}
function badge(p){return `<span class="badge ${p.status==='paused'?'paused':p.status==='done'?'done':''}">${p.status==='done'?i('check','icon-sm'):''}${statuses[p.status]}</span>`;}
function projectCard(p){const c=categories[p.category],q=progress(p.id);return `<button class="project-card" data-action="project" data-id="${p.id}" aria-label="Открыть проект ${esc(p.name)}"><div class="project-top"><span class="project-symbol ${c.color}">${i(c.icon)}</span><div class="project-title"><h3>${esc(p.name)}</h3><p>${esc(p.client||c.label)} · ${money(p.budget)}</p></div>${i('chevron')}</div><div class="project-meta">${badge(p)}<span class="deadline ${p.deadline&&p.deadline<day()&&p.status!=='done'?'overdue':''}">${i('calendar','icon-sm')}${p.deadline?prettyDate(p.deadline):'Без срока'}</span></div><div class="mini-progress"><div class="track"><span style="width:${q.percent}%"></span></div><small>${q.done}/${q.all} задач</small></div></button>`;}
function taskRow(t){const p=getProject(t.project);return `<div class="task-row ${t.done?'complete':''}"><button class="check-btn ${t.done?'checked':''}" data-action="toggle-task" data-id="${t.id}" role="checkbox" aria-checked="${t.done}" aria-label="${t.done?'Вернуть':'Выполнить'}: ${esc(t.title)}">${t.done?i('check'):''}</button><button class="task-body" data-action="edit-task" data-id="${t.id}"><b>${esc(t.title)}</b><small>${t.priority==='high'?'<span class="priority-dot high"></span>':''}${esc(p?.name||'Личная задача')}</small></button><span class="task-date ${!t.done&&t.due&&t.due<day()?'overdue':''}">${t.due?when(t.due):''}</span></div>`;}
function paymentRow(p){return `<div class="payment"><span class="payment-icon">${i('receipt')}</span><button class="payment-body" data-action="edit-payment" data-id="${p.id}"><b>${esc(getProject(p.project)?.name||p.projectName||'Доход без проекта')}</b><small>${prettyDate(p.date)}${p.note?' · '+esc(p.note):''}</small></button><span class="payment-amount">+${money(p.amount)}</span></div>`;}
function empty(icon,title,desc,action,label){return `<div class="empty"><span class="empty-icon">${i(icon,'icon-lg')}</span><h3>${esc(title)}</h3><p>${esc(desc)}</p>${action?`<button class="btn secondary" data-action="${action}">${i('plus')}${esc(label)}</button>`:''}</div>`;}
function warning(){return recovery?'<div class="recovery">Не удалось прочитать сохранение. Исходные данные не перезаписаны. Откройте настройки, чтобы экспортировать их и восстановить копию.</div>':saveFailed?'<div class="recovery">Изменения не сохранены. Проверьте свободное место или экспортируйте данные.</div>':'';}
function home(){
 const m=monthKey(new Date()),income=sumMonth(m),goal=state.profile.goal,percent=Math.round(income/goal*100),projects=state.projects.filter(p=>p.status!=='done'),tasks=state.tasks.filter(t=>!t.done&&t.due&&t.due<=day()).sort((a,b)=>a.due.localeCompare(b.due)||Number(b.priority==='high')-Number(a.priority==='high'));
 return `<div class="greeting"><div><div class="eyebrow">${new Date().toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}</div><h1>В твоём ритме, ${esc(state.profile.name.split(' ')[0])}.</h1><p>Меньше суеты. Больше любимого дела.</p></div><span class="sun">${i('sun','icon-lg')}</span></div><div class="overview-grid"><div class="desktop-left"><section class="hero" aria-label="Доход за текущий месяц"><div class="hero-top"><span class="eyebrow">Заработано за месяц</span><span class="period">${i('calendar','icon-sm')}${new Date().toLocaleDateString('ru-RU',{month:'long'})}</span></div><div><div class="balance">${number(income)} <span>₽</span></div><div class="hero-sub">${income>=goal?'Отличная работа. Цель месяца достигнута.':'Каждый проект — шаг к большой цели.'}</div></div><div class="hero-bottom"><div class="goal-line"><div class="goal-label"><span>Цель ${money(goal)}</span><span>${percent}%</span></div><div class="progress-track" role="progressbar" aria-valuenow="${Math.min(percent,100)}" aria-valuemin="0" aria-valuemax="100" aria-label="Цель дохода"><span style="width:${Math.min(percent,100)}%"></span></div></div><button class="hero-btn" data-action="new-payment" aria-label="Записать доход">${i('plus')}</button></div></section><div class="stats"><button class="stat" data-action="tab" data-tab="projects"><span class="stat-icon">${i('projects')}</span><span><b>${projects.length}</b><small>открытых проектов</small></span></button><button class="stat" data-action="tab" data-tab="tasks"><span class="stat-icon">${i('bolt')}</span><span><b>${tasks.length}</b><small>задач на сегодня*</small></span></button></div><section class="section"><div class="section-head"><h2>Сегодня в фокусе</h2><button class="text-btn" data-action="new-task">${i('plus','icon-sm')} Задача</button></div>${tasks.length?`<div class="task-list">${tasks.slice(0,4).map(taskRow).join('')}</div>`:empty('coffee','Можно выдохнуть','На сегодня всё. Добавьте задачу или загляните в проекты.','new-task','Добавить задачу')}<p class="inline-note">${i('info')}* Здесь также задачи с прошедшим сроком.</p></section></div><div class="desktop-right"><section class="section"><div class="section-head"><h2>Мои проекты <small>${projects.length}</small></h2><button class="text-btn" data-action="tab" data-tab="projects">Все ${i('arrow','icon-sm')}</button></div><div class="project-list">${projects.slice(0,3).map(projectCard).join('')}</div>${!projects.length?empty('folder','Место для новой идеи','Добавьте первый проект и соберите всё важное в одном месте.','new-project','Новый проект'):''}</section><p class="inline-note">${i('shield')}Данные хранятся только на этом устройстве.${state.demo?'<span class="demo-tag">ДЕМО</span>':''}</p></div></div>`;
}
function projectsPage(){
 const q=ui.query.toLocaleLowerCase('ru-RU');const projects=state.projects.filter(p=>(ui.projectFilter==='all'||p.status===ui.projectFilter)&&(!q||(p.name+' '+p.client).toLocaleLowerCase('ru-RU').includes(q))).sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||(a.deadline||'9999').localeCompare(b.deadline||'9999'));
 return `<div class="page-body"><div class="page-header"><div><h1>Мои проекты</h1><p>От первой идеи до финального «готово».</p></div><button class="round-add" data-action="new-project" aria-label="Добавить проект">${i('plus')}</button></div><label class="search">${i('search')}<input id="project-search" type="search" placeholder="Название или клиент" value="${esc(ui.query)}" aria-label="Поиск проектов" maxlength="80"></label><div class="chips" role="group" aria-label="Фильтр проектов">${[['all','Все'],['active','В работе'],['paused','На паузе'],['done','Готово']].map(([key,label])=>`<button class="chip ${ui.projectFilter===key?'active':''}" data-action="project-filter" data-filter="${key}" aria-pressed="${ui.projectFilter===key}">${label}<small>${state.projects.filter(p=>key==='all'||p.status===key).length}</small></button>`).join('')}</div><div id="project-results"><div class="project-list">${projects.map(projectCard).join('')}</div>${!projects.length?empty('search',q?'Ничего не найдено':'Пока без проектов',q?'Попробуйте другое название или имя клиента.':'Здесь появятся ваши проекты, сроки и прогресс.',q?'':'new-project','Создать проект'):''}</div></div>`;
}
function tasksPage(){
 const due=day(),week=day(6),all=state.tasks;
 const filtered=all.filter(t=>ui.taskFilter==='done'?t.done:!t.done&&(ui.taskFilter==='all'||ui.taskFilter==='today'&&t.due&&t.due<=due||ui.taskFilter==='week'&&t.due&&t.due<=week)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||Number(b.priority==='high')-Number(a.priority==='high'));
 const done=all.filter(t=>t.done).length;
 return `<div class="page-body"><div class="page-header"><div><h1>Одна за другой.</h1><p>Большие проекты начинаются с малого.</p></div><button class="round-add" data-action="new-task" aria-label="Добавить задачу">${i('plus')}</button></div><div class="task-summary"><div><b>${done}<span class="muted" style="font-size:16px;font-weight:400"> / ${all.length}</span></b><p>задач уже позади</p></div>${i('tasks')}</div><div class="chips" role="group" aria-label="Фильтр задач">${[['today','Сегодня'],['week','7 дней'],['all','Все'],['done','Готово']].map(([key,label])=>`<button class="chip ${ui.taskFilter===key?'active':''}" data-action="task-filter" data-filter="${key}" aria-pressed="${ui.taskFilter===key}">${label}</button>`).join('')}</div><div class="section-head"><h2>${{today:'Сегодня и раньше',week:'Ближайшие 7 дней',all:'Открытые задачи',done:'Выполненные'}[ui.taskFilter]} <small>${filtered.length}</small></h2></div>${filtered.length?`<div class="task-list">${filtered.map(taskRow).join('')}</div>`:empty('coffee',ui.taskFilter==='done'?'Первая победа впереди':'Всё под контролем',ui.taskFilter==='done'?'Отметьте задачу выполненной — она появится здесь.':'В этом разделе пока нет задач. Хороший момент спланировать следующий шаг.','new-task','Новая задача')}<p class="inline-note">${i('info')}${ui.taskFilter==='today'||ui.taskFilter==='week'?'Включая невыполненные задачи с прошедшим сроком.':'Нажмите на задачу, чтобы изменить её.'}</p></div>`;
}
function incomePage(){
 const d=parseDate(ui.month+'-01'),total=sumMonth(ui.month),payments=state.payments.filter(p=>p.date.startsWith(ui.month)).sort((a,b)=>b.date.localeCompare(a.date)),months=Array.from({length:6},(_,j)=>{const x=new Date(d.getFullYear(),d.getMonth()-5+j,1);return {key:monthKey(x),label:x.toLocaleDateString('ru-RU',{month:'short'}).replace('.',''),value:sumMonth(monthKey(x))};}),max=Math.max(...months.map(m=>m.value),1);
 return `<div class="page-body"><div class="page-header"><div><h1>Плоды твоего дела.</h1><p>Всё, что принесли ваши проекты.</p></div><button class="round-add" data-action="new-payment" aria-label="Записать доход">${i('plus')}</button></div><div class="month-row"><button class="icon-btn" data-action="month" data-delta="-1" aria-label="Предыдущий месяц">${i('left')}</button><b>${monthLabel(d)}</b><button class="icon-btn" data-action="month" data-delta="1" aria-label="Следующий месяц">${i('right')}</button></div><div class="income-total"><small>Получено за месяц${state.demo?' · демо':''}</small><strong>${money(total)}</strong><p>${payments.length} ${payments.length===1?'платёж':payments.length<5&&payments.length>0?'платежа':'платежей'} · ${Math.round(total/state.profile.goal*100)}% от месячной цели</p></div><div class="chart-panel"><div class="chart-head"><b>Работа приносит результат</b><small>6 месяцев</small></div><div class="chart" role="img" aria-label="Доход по месяцам: ${months.map(m=>m.label+' '+money(m.value)).join('; ')}">${months.map(m=>`<div class="chart-col"><div class="chart-bar ${m.key===ui.month?'current':''}" style="height:${Math.max(3,m.value/max*103)}px" title="${m.label}: ${money(m.value)}"></div><small>${m.label}</small></div>`).join('')}</div></div><section class="section"><div class="section-head"><h2>История поступлений</h2><span class="small muted">${payments.length}</span></div>${payments.length?payments.map(paymentRow).join(''):empty('wallet','Пока нет поступлений','Записывайте фактически полученные платежи. Бюджеты проектов сюда не добавляются автоматически.','new-payment','Записать доход')}</section><div class="finance-note">${i('info')}Это учёт поступлений, а не чистой прибыли. Расходы, налоги и комиссии не рассчитываются.</div></div>`;
}
function detailPage(){const p=getProject(ui.project);if(!p){ui.project=null;return projectsPage();}const c=categories[p.category],q=progress(p.id),payed=paid(p.id),tasks=state.tasks.filter(t=>t.project===p.id).sort((a,b)=>Number(a.done)-Number(b.done)),payments=state.payments.filter(r=>r.project===p.id).sort((a,b)=>b.date.localeCompare(a.date));
 return `<div class="page-body"><div class="detail-top"><button class="text-btn" data-action="back-projects">${i('back')} К проектам</button><button class="icon-btn bare" data-action="edit-project" data-id="${p.id}" aria-label="Редактировать проект" style="margin-left:auto">${i('edit')}</button></div><div class="detail-identity"><span class="project-symbol ${c.color}">${i(c.icon,'icon-lg')}</span><h1>${esc(p.name)}</h1><p>${esc(p.client||'Без клиента')} · ${c.label}</p><div class="detail-chips">${badge(p)}<span class="badge">${i('calendar','icon-sm')}${p.deadline?prettyDate(p.deadline,true):'Без срока'}</span></div></div><div class="money-grid"><div class="money-cell"><small>Бюджет проекта</small><b>${money(p.budget)}</b></div><div class="money-cell green"><small>Уже получено</small><b>${money(payed)}</b></div></div><p class="small muted" style="margin-bottom:18px">${payed>p.budget?'Сверх бюджета: '+money(payed-p.budget):'Осталось получить: '+money(p.budget-payed)}</p><div class="detail-actions"><button class="btn" data-action="new-task" data-project="${p.id}">${i('plus')} Задача</button><button class="btn secondary" data-action="new-payment" data-project="${p.id}">${i('wallet')} Оплата</button></div>${p.notes?`<p class="detail-note">${esc(p.notes)}</p>`:''}<section class="section"><div class="section-head"><h2>Шаги к результату <small>${q.done}/${q.all}</small></h2><span class="small muted">${q.percent}%</span></div>${tasks.length?`<div class="task-list">${tasks.map(taskRow).join('')}</div>`:empty('tasks','Наметим первые шаги','Разбейте работу на конкретные задачи.','new-task','Добавить задачу')}</section>${payments.length?`<section class="section"><div class="section-head"><h2>Платежи по проекту</h2></div>${payments.map(paymentRow).join('')}</section>`:''}</div>`;
}
function render(){applyTheme();const initial=state.profile.name.trim().slice(0,2).toUpperCase();$('#app').innerHTML=`<div class="shell"><header class="topbar"><button class="brand" data-action="tab" data-tab="home" aria-label="Folio: обзор"><span class="brandmark">${i('brand')}</span>folio<span style="color:#98aa83">.</span></button><div class="topright"><span class="offline">local-first</span>${state.demo?'<span class="demo-tag">ДЕМО</span>':''}<button class="icon-btn" data-action="settings" aria-label="Настройки">${i('settings')}</button><button class="icon-btn avatar" data-action="profile" aria-label="Профиль">${esc(initial)}</button></div></header>${warning()}<main class="page-enter">${ui.project?detailPage():{home,projects:projectsPage,tasks:tasksPage,income:incomePage}[ui.tab]()}</main></div><nav class="bottom-nav" aria-label="Основная навигация"><div class="nav-inner">${[['home','Обзор'],['projects','Проекты'],['tasks','Задачи'],['income','Доходы']].map(([key,title])=>`<button class="nav-item ${ui.tab===key?'active':''}" data-action="tab" data-tab="${key}" ${ui.tab===key?'aria-current="page"':''}><span>${i(key)}</span>${title}</button>`).join('')}</div></nav>`;renderModal();}
function navigate(tab,project=null){ui.tab=tab;ui.project=project;ui.modal=null;ui.query='';history.pushState({tab,project},'',`#${project?'project-'+project:tab}`);render();window.scrollTo(0,0);}
function openModal(name,data=null,replace=false){ui.modal=name;ui.modalData=data;if(!replace)history.pushState({tab:ui.tab,project:ui.project,modal:name,modalData:data},'',`#${name}`);else history.replaceState({tab:ui.tab,project:ui.project,modal:name,modalData:data},'',`#${name}`);renderModal();}
function closeModal(){if(history.state?.modal)history.back();else{ui.modal=null;renderModal();}}
function options(values,current,blank){return (blank!==undefined?`<option value="">${esc(blank)}</option>`:'')+Object.entries(values).map(([v,label])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label)}</option>`).join('');}
function projectOptions(current){return options(Object.fromEntries(state.projects.map(p=>[p.id,p.name])),current,'Без проекта');}
function field(name,label,value='',type='text',extra=''){return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function projectForm(p){return `<form id="project-form"><input type="hidden" name="id" value="${p?.id||''}">${field('name','Название проекта',p?.name||'','text','required maxlength="80" placeholder="Например, сайт студии"')}${field('client','Клиент',p?.client||'','text','maxlength="60" placeholder="Компания или имя"')}<div class="form-grid">${field('budget','Бюджет, ₽',p?.budget??'','number','min="0" max="999999999" step="0.01" required placeholder="0" inputmode="decimal"')}${field('deadline','Дедлайн',p?.deadline||'','date','min="2000-01-01" max="2100-12-31"')}</div><div class="form-grid"><label class="field"><span>Направление</span><select name="category">${options(Object.fromEntries(Object.entries(categories).map(([k,v])=>[k,v.label])),p?.category||'design')}</select></label><label class="field"><span>Статус</span><select name="status">${options(statuses,p?.status||'active')}</select></label></div><label class="field"><span>Заметки</span><textarea name="notes" maxlength="2000" placeholder="Что важно не забыть">${esc(p?.notes||'')}</textarea></label><div class="form-actions">${p?`<button type="button" class="btn ghost" data-action="delete-project" data-id="${p.id}" aria-label="Удалить проект">${i('trash')}</button>`:''}<button type="submit" class="btn">${i('check')}${p?'Сохранить изменения':'Создать проект'}</button></div><p class="form-help">Бюджет — ожидаемая сумма. Фактические поступления записываются отдельно.</p></form>`;}
function taskForm(t,project){return `<form id="task-form"><input type="hidden" name="id" value="${t?.id||''}">${field('title','Что нужно сделать?',t?.title||'','text','required maxlength="160" placeholder="Один понятный шаг"')}<label class="field"><span>Проект</span><select name="project">${projectOptions(t?.project||project||'')}</select></label><div class="form-grid">${field('due','Срок',t?t.due:day(),'date','min="2000-01-01" max="2100-12-31"')}<label class="field"><span>Приоритет</span><select name="priority">${options(priorities,t?.priority||'normal')}</select></label></div><div class="form-actions">${t?`<button type="button" class="btn ghost" data-action="delete-task" data-id="${t.id}" aria-label="Удалить задачу">${i('trash')}</button>`:''}<button type="submit" class="btn">${i('check')}${t?'Сохранить':'Добавить задачу'}</button></div></form>`;}
function paymentForm(p,project){return `<form id="payment-form"><input type="hidden" name="id" value="${p?.id||''}">${field('amount','Полученная сумма, ₽',p?.amount??'','number','required min="0.01" max="999999999" step="0.01" placeholder="0" inputmode="decimal"')}<label class="field"><span>Проект</span><select name="project">${projectOptions(p?.project||project||'')}</select></label>${field('date','Дата поступления',p?.date||day(),'date','required min="2000-01-01" max="'+day()+'"')}${field('note','Комментарий',p?.note||'','text','maxlength="200" placeholder="Например, предоплата 50%"')}<div class="form-actions">${p?`<button type="button" class="btn ghost" data-action="delete-payment" data-id="${p.id}" aria-label="Удалить платёж">${i('trash')}</button>`:''}<button type="submit" class="btn">${i('check')}${p?'Сохранить':'Записать доход'}</button></div><p class="form-help">Добавляйте только уже полученные деньги. Folio не проводит банковские операции.</p></form>`;}
function settings(){return `<div class="settings-section"><div class="eyebrow">Личное пространство</div><button class="settings-row" data-action="profile">${i('edit')}<span><b>${esc(state.profile.name)}</b><small>Имя и месячная цель</small></span>${i('chevron')}</button><div class="theme-picker">${[['light','Светлая'],['dark','Тёмная'],['system','Система']].map(([key,label])=>`<button class="chip ${state.profile.theme===key?'active':''}" data-action="theme" data-theme="${key}" aria-pressed="${state.profile.theme===key}">${label}</button>`).join('')}</div></div><div class="settings-section"><div class="eyebrow">Мои данные</div><button class="settings-row" data-action="export">${i('download')}<span><b>Резервная копия</b><small>Сохранить проекты, задачи и платежи</small></span>${i('chevron')}</button><button class="settings-row" data-action="import">${i('upload')}<span><b>Восстановить из копии</b><small>Заменить данные сохранённой копией</small></span>${i('chevron')}</button>${installPrompt?`<button class="settings-row" data-action="install">${i('phone')}<span><b>Установить Folio</b><small>Добавить приложение на главный экран</small></span>${i('chevron')}</button>`:''}</div><div class="settings-section"><div class="eyebrow">Начать по-своему</div><button class="settings-row" data-action="demo">${i('spark')}<span><b>Загрузить демо-проекты</b><small>Заменит текущие данные примерами</small></span>${i('chevron')}</button><button class="settings-row danger" data-action="reset">${i('trash')}<span><b>Очистить проекты и доходы</b><small>Начать с пустого рабочего пространства</small></span>${i('chevron')}</button></div><div class="info-box">${i('shield','icon-sm')} Никаких аккаунтов и аналитики. Данные хранятся локально. При удалении приложения или очистке данных браузера они удалятся — сохраняйте резервную копию.</div><div class="version">folio. · версия 1.0.0<br>Проекты. Задачи. Спокойствие.<br>Иконки: Font Awesome Free · CC BY 4.0</div>`;}
let confirmation=null;
function ask(title,text,fn){confirmation=fn;openModal('confirm',{title,text},!!ui.modal);}
function renderModal(){
 const root=$('#modal-root');if(!ui.modal){root.innerHTML='';document.body.style.overflow='';return;}document.body.style.overflow='hidden';const d=ui.modalData||{};let title='',body='';
 if(ui.modal==='project-form'){const p=d.id?getProject(d.id):null;title=p?'Изменить проект':'Новая глава.';body=projectForm(p);}
 if(ui.modal==='task-form'){const t=state.tasks.find(x=>x.id===d.id);title=t?'Изменить задачу':'Маленький шаг.';body=taskForm(t,d.project);}
 if(ui.modal==='payment-form'){const p=state.payments.find(x=>x.id===d.id);title=p?'Изменить платёж':'Хорошие новости.';body=paymentForm(p,d.project);}
 if(ui.modal==='settings'){title='Твоё пространство.';body=settings();}
 if(ui.modal==='profile'){title='Знакомство с тобой.';body=`<form id="profile-form">${field('name','Как тебя зовут?',state.profile.name,'text','required maxlength="40"')}${field('goal','Цель дохода на месяц, ₽',state.profile.goal,'number','required min="1" max="999999999" step="1" inputmode="numeric"')}<button class="btn full" type="submit">Сохранить</button><p class="form-help">Цель применяется к отображению всех месяцев. Валюта учёта — российский рубль.</p></form>`;}
 if(ui.modal==='confirm'){title=esc(d.title);body=`<p class="confirm-text">${esc(d.text)}</p><div class="form-actions"><button class="btn ghost" data-action="close">Отмена</button><button class="btn danger" data-action="confirm">Подтвердить</button></div>`;}
 if(ui.modal==='export'){title='Пусть всё сохранится.';const raw=recovery?(localStorage.getItem(KEY)||''):JSON.stringify(state,null,2);body=`<p class="form-help" style="margin:0 0 15px">${recovery?'Исходное сохранение не удалось прочитать. Скопируйте его, прежде чем восстанавливать данные.':'Скопируйте текст целиком в файл или сохраните JSON. Копия содержит все ваши данные; храните её в безопасном месте.'}</p><textarea id="backup-text" class="field backup-field" readonly style="width:100%;padding:12px;background:var(--paper);color:var(--text);border:1px solid var(--line);border-radius:12px">${esc(raw)}</textarea><div class="form-actions"><button class="btn" data-action="copy">${i('copy')}Скопировать</button>${isNative()?'':`<button class="btn secondary" data-action="download">${i('download')}JSON</button>`}</div>${isNative()?'<p class="form-help">На Android нажмите «Скопировать» и вставьте текст в заметки или сохраните его в текстовый файл.</p>':''}`;}
 if(ui.modal==='import'){title='Всё на своих местах.';body=`<p class="form-help" style="margin:0 0 15px">Вставьте текст копии Folio. После проверки приложение попросит подтвердить замену текущих данных.</p>${isNative()?'':'<label class="field"><span>Или выберите JSON-файл</span><input id="import-file" type="file" accept=".json,application/json"></label>'}<label class="field"><span>Текст резервной копии</span><textarea id="import-text" class="backup-field" placeholder=\'{"version":1,...}\' spellcheck="false"></textarea></label><button class="btn full" data-action="check-import">Проверить и восстановить</button>`;}
 root.innerHTML=`<div class="backdrop" data-backdrop="true"><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title"><div class="handle"></div><div class="sheet-head"><h2 id="sheet-title">${title}</h2><button class="icon-btn" data-action="close" aria-label="Закрыть">${i('close')}</button></div>${body}</section></div>`;
 // Avoid opening the keyboard automatically on touch devices.
 if(matchMedia('(pointer:fine)').matches)setTimeout(()=>root.querySelector('input:not([type=hidden]),button')?.focus(),70);
}
function isNative(){return /; wv\)/.test(navigator.userAgent)||location.protocol==='file:'&&/Android/i.test(navigator.userAgent);}
function deleteEntity(type,id){const names={project:['Удалить проект?','Задачи проекта будут удалены. Уже записанные поступления останутся в истории доходов без привязки к проекту.'],task:['Удалить задачу?','Это действие нельзя отменить.'],payment:['Удалить платёж?','Он исчезнет из истории и больше не будет учитываться в доходах.']};ask(...names[type],()=>{if(commit(()=>{if(type==='project'){const p=getProject(id);state.projects=state.projects.filter(x=>x.id!==id);state.tasks=state.tasks.filter(x=>x.project!==id);state.payments=state.payments.map(r=>r.project===id?{...r,project:'',projectName:p?.name||r.projectName}:r);ui.project=null;}else if(type==='task'){state.tasks=state.tasks.filter(x=>x.id!==id);}else{state.payments=state.payments.filter(x=>x.id!==id);}},'Удалено')){closeModal();render();}});}
function parseBackup(raw){if(raw.length>MAX)throw Error('Файл слишком большой. Максимум 2,5 МБ.');return validate(JSON.parse(raw));}
function downloadBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`folio-backup-${day()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function onAction(el){const a=el.dataset.action,id=el.dataset.id;
 switch(a){
 case 'tab':navigate(el.dataset.tab);break;
 case 'project':navigate('projects',id);break;
 case 'back-projects':navigate('projects');break;
 case 'project-filter':ui.projectFilter=el.dataset.filter;render();break;
 case 'task-filter':ui.taskFilter=el.dataset.filter;render();break;
 case 'new-project':openModal('project-form');break;
 case 'edit-project':openModal('project-form',{id});break;
 case 'new-task':openModal('task-form',{project:el.dataset.project||ui.project||''});break;
 case 'edit-task':openModal('task-form',{id});break;
 case 'new-payment':openModal('payment-form',{project:el.dataset.project||ui.project||''});break;
 case 'edit-payment':openModal('payment-form',{id});break;
 case 'toggle-task':if(commit(()=>{const t=state.tasks.find(t=>t.id===id);if(t)t.done=!t.done;})){render();}break;
 case 'delete-project':deleteEntity('project',id);break;
 case 'delete-task':deleteEntity('task',id);break;
 case 'delete-payment':deleteEntity('payment',id);break;
 case 'settings':openModal('settings',null,!!ui.modal);break;
 case 'profile':openModal('profile',null,!!ui.modal);break;
 case 'theme':if(commit(()=>state.profile.theme=el.dataset.theme)){applyTheme();renderModal();}break;
 case 'close':closeModal();break;
 case 'month':{const d=parseDate(ui.month+'-01');d.setMonth(d.getMonth()+Number(el.dataset.delta));ui.month=monthKey(d);render();break;}
 case 'confirm':{const fn=confirmation;confirmation=null;if(fn)fn();else closeModal();break;}
 case 'export':openModal('export',null,!!ui.modal);break;
 case 'import':openModal('import',null,!!ui.modal);break;
 case 'download':downloadBackup();break;
 case 'copy':{const text=$('#backup-text');text.focus();text.select();try{if(document.execCommand('copy'))toast('Копия в буфере обмена');else if(navigator.clipboard){navigator.clipboard.writeText(text.value).then(()=>toast('Копия в буфере обмена')).catch(()=>toast('Выделите текст и скопируйте его вручную.',true));}else toast('Текст выделен. Нажмите «Копировать».');}catch(e){toast('Текст выделен. Скопируйте его вручную.');}break;}
 case 'check-import':{try{const next=parseBackup($('#import-text').value);ask('Восстановить копию?',`Текущие данные заменятся: ${next.projects.length} проектов, ${next.tasks.length} задач, ${next.payments.length} платежей. Предварительно сохраните свою копию.`,()=>{const old=state,wasRecovery=recovery;state=next;recovery=false;if(save()){ui.project=null;closeModal();render();toast('Резервная копия восстановлена');}else{state=old;recovery=wasRecovery;render();}});}catch(e){toast(e instanceof SyntaxError?'Некорректный JSON. Вставьте текст копии целиком.':e.message,true);}break;}
 case 'reset':ask('Начать с чистого листа?','Все проекты, задачи и платежи на этом устройстве будут удалены. Сначала сохраните резервную копию. Имя, тема и месячная цель останутся.',()=>{const prev=state,wasRecovery=recovery;state={version:1,demo:false,profile:{...state.profile},projects:[],tasks:[],payments:[]};recovery=false;if(save()){ui.project=null;closeModal();render();toast('Готово. Это ваше пространство.');}else{state=prev;recovery=wasRecovery;render();}});break;
 case 'demo':ask('Загрузить примеры?','Текущие проекты, задачи и доходы заменятся демонстрационными. Сохраните резервную копию перед продолжением.',()=>{const prev=state,wasRecovery=recovery;state=seed();recovery=false;if(save()){ui.project=null;closeModal();render();toast('Демо-проекты загружены');}else{state=prev;recovery=wasRecovery;render();}});break;
 case 'install':if(installPrompt){installPrompt.prompt();installPrompt.userChoice.then(()=>{installPrompt=null;renderModal();});}break;
 }
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el){e.preventDefault();onAction(el);}else if(e.target.dataset.backdrop){closeModal();}});
document.addEventListener('input',e=>{if(e.target.id==='project-search'){const pos=e.target.selectionStart;ui.query=e.target.value;const temp=document.createElement('div');temp.innerHTML=projectsPage();$('#project-results').innerHTML=temp.querySelector('#project-results').innerHTML;}});
document.addEventListener('change',async e=>{if(e.target.id==='import-file'){const file=e.target.files[0];if(!file)return;if(file.size>MAX){toast('Файл больше 2,5 МБ.',true);return;}try{$('#import-text').value=await file.text();}catch(err){toast('Не удалось прочитать файл.',true);}}});
document.addEventListener('submit',e=>{
 e.preventDefault();const f=e.target,fid=f.getAttribute('id');if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));let message='';
 if(fid==='project-form'){
  if(!d.name.trim()){toast('Введите название проекта.',true);return;}
  if(d.deadline&&!validDate(d.deadline)){toast('Проверьте дедлайн.',true);return;}
  const p={id:d.id||uid(),name:d.name.trim(),client:d.client.trim(),budget:Math.round(Number(d.budget)*100)/100,deadline:d.deadline,category:d.category,status:d.status,notes:d.notes.trim(),created:getProject(d.id)?.created||day()};
  message=d.id?'Проект обновлён':'Новая глава началась';if(!commit(()=>{const index=state.projects.findIndex(x=>x.id===d.id);if(index>=0)state.projects[index]=p;else state.projects.unshift(p);},message))return;
 }else if(fid==='task-form'){
  if(!d.title.trim()){toast('Введите название задачи.',true);return;}
  const t={id:d.id||uid(),title:d.title.trim(),project:d.project,due:d.due,priority:d.priority,done:state.tasks.find(x=>x.id===d.id)?.done||false};
  if(!commit(()=>{const index=state.tasks.findIndex(x=>x.id===d.id);if(index>=0)state.tasks[index]=t;else state.tasks.push(t);},d.id?'Задача обновлена':'Задача добавлена'))return;
 }else if(fid==='payment-form'){
  if(!validDate(d.date)||d.date>day()){toast('Укажите дату уже полученного платежа.',true);return;}
  const p={id:d.id||uid(),project:d.project,projectName:getProject(d.project)?.name||state.payments.find(x=>x.id===d.id)?.projectName||'',amount:Math.round(Number(d.amount)*100)/100,date:d.date,note:d.note.trim()};
  if(!commit(()=>{const index=state.payments.findIndex(x=>x.id===d.id);if(index>=0)state.payments[index]=p;else state.payments.unshift(p);},d.id?'Платёж обновлён':'Доход записан. Отличная работа!'))return;
 }else if(fid==='profile-form'){
  if(!d.name.trim()){toast('Введите имя.',true);return;}
  if(!commit(()=>{state.profile.name=d.name.trim();state.profile.goal=Number(d.goal);},'Настройки сохранены'))return;
 }else return;
 closeModal();render();
});
window.addEventListener('popstate',e=>{const s=e.state||{tab:'home'};ui.tab=['home','projects','tasks','income'].includes(s.tab)?s.tab:'home';ui.project=s.project||null;ui.modal=s.modal||null;ui.modalData=s.modalData||null;render();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&ui.modal){e.preventDefault();closeModal();}if(e.key==='Tab'&&ui.modal){const els=[...$('#modal-root').querySelectorAll('button,input:not([type=hidden]),select,textarea,a[href]')].filter(x=>!x.disabled);if(!els.length)return;const a=els[0],z=els[els.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();z.focus();}else if(!e.shiftKey&&document.activeElement===z){e.preventDefault();a.focus();}}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{state=validate(JSON.parse(e.newValue));if(!ui.modal)render();}catch(err){toast('Данные изменились в другой вкладке, но не прошли проверку.',true);}}});
matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.profile.theme==='system')applyTheme();});
load();history.replaceState({tab:'home'},'','#home');render();
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol)){navigator.serviceWorker.register('sw.js').catch(()=>{});}
// Read-only diagnostics and validator are useful for automated tests and debugging.
window.Folio={version:'1.0.0',validateBackup:validate,snapshot:()=>JSON.parse(JSON.stringify(state)),storageKey:KEY};
})();
